// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    accounts_by_industry: {
        name: "accounts_by_industry";
        parameters: Record<string, never>;
        result: Array<{
          /** Represents the industry the account belongs to, allowing for categorization and segmentation. */
          industry: string;
          /** @sqlType BIGINT */
          account_count: number;
          /** @sqlType DOUBLE */
          total_revenue: number;
          /** @sqlType DOUBLE */
          avg_revenue: number;
        }>;
      };
    accounts_by_region: {
        name: "accounts_by_region";
        parameters: Record<string, never>;
        result: Array<{
          /** The region of the account, providing a more granular geographical segmentation. */
          region: string;
          /** @sqlType BIGINT */
          account_count: number;
          /** @sqlType DOUBLE */
          total_revenue: number;
        }>;
      };
    opportunity_trend: {
        name: "opportunity_trend";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType TIMESTAMP */
          month: string;
          /** @sqlType BIGINT */
          num_opportunities: number;
          /** @sqlType DOUBLE */
          total_amount: number;
        }>;
      };
    pipeline_by_stage: {
        name: "pipeline_by_stage";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          stagename: string;
          /** @sqlType BIGINT */
          deal_count: number;
          /** @sqlType DOUBLE */
          total_amount: number;
          /** @sqlType DOUBLE */
          avg_amount: number;
        }>;
      };
    pipeline_history: {
        name: "pipeline_history";
        parameters: Record<string, never>;
        result: Array<{
          /** Represents the current stage of the sales opportunity. */
          dealstage: string;
          /** @sqlType DOUBLE */
          total_deal_amount: number;
          /** @sqlType BIGINT */
          record_count: number;
        }>;
      };
    pipeline_kpis: {
        name: "pipeline_kpis";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          total_opportunities: number;
          /** @sqlType DOUBLE */
          total_pipeline: number;
          /** @sqlType DOUBLE */
          avg_deal_size: number;
          /** @sqlType BIGINT */
          closed_won: number;
          /** @sqlType BIGINT */
          closed_lost: number;
          /** @sqlType DOUBLE */
          open_pipeline: number;
          /** @sqlType DOUBLE */
          weighted_pipeline: number;
        }>;
      };
    table_summary: {
        name: "table_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          table_name: string;
          /** @sqlType BIGINT */
          row_count: number;
        }>;
      };
    top_reps: {
        name: "top_reps";
        parameters: Record<string, never>;
        result: Array<{
          /** The user's name, providing a human-readable label for identification. */
          rep_name: string;
          /** @sqlType BIGINT */
          deal_count: number;
          /** @sqlType DOUBLE */
          total_amount: number;
          /** @sqlType DOUBLE */
          avg_deal_size: number;
        }>;
      };
  }
}
